//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 04:34:21 PM EDT 
//


package com.dialogic.xms.msml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for basicStreamType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="basicStreamType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dir" type="{}streamDir.datatype" />
 *       &lt;attribute name="media" type="{}streamMedia.datatype" />
 *       &lt;attribute name="compressed" type="{}boolean.datatype" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "basicStreamType")
@XmlSeeAlso({
    StreamType.class
})
public class BasicStreamType {

    @XmlAttribute(name = "dir")
    protected StreamDirDatatype dir;
    @XmlAttribute(name = "media")
    protected StreamMediaDatatype media;
    @XmlAttribute(name = "compressed")
    protected BooleanDatatype compressed;

    /**
     * Gets the value of the dir property.
     * 
     * @return
     *     possible object is
     *     {@link StreamDirDatatype }
     *     
     */
    public StreamDirDatatype getDir() {
        return dir;
    }

    /**
     * Sets the value of the dir property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamDirDatatype }
     *     
     */
    public void setDir(StreamDirDatatype value) {
        this.dir = value;
    }

    /**
     * Gets the value of the media property.
     * 
     * @return
     *     possible object is
     *     {@link StreamMediaDatatype }
     *     
     */
    public StreamMediaDatatype getMedia() {
        return media;
    }

    /**
     * Sets the value of the media property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamMediaDatatype }
     *     
     */
    public void setMedia(StreamMediaDatatype value) {
        this.media = value;
    }

    /**
     * Gets the value of the compressed property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanDatatype }
     *     
     */
    public BooleanDatatype getCompressed() {
        return compressed;
    }

    /**
     * Sets the value of the compressed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanDatatype }
     *     
     */
    public void setCompressed(BooleanDatatype value) {
        this.compressed = value;
    }

}
