//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 04:34:21 PM EDT 
//


package com.dialogic.xms.msml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}primitiveType">
 *       &lt;sequence>
 *         &lt;element name="sendobj" type="{}sendobjType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="hdrfooter" type="{}hdrfooterType" minOccurs="0"/>
 *         &lt;element name="rxpoll" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rcvobj" type="{}rcvobjType" maxOccurs="unbounded"/>
 *                   &lt;element name="hdrfooter" type="{}hdrfooterType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="rmtid" use="required" type="{}faxid.datatype" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;group ref="{}faxstatusrequest"/>
 *       &lt;/sequence>
 *       &lt;attribute name="lclid" type="{}faxid.datatype" />
 *       &lt;attribute name="minspeed" type="{}faxspeed.datatype" />
 *       &lt;attribute name="maxspeed" type="{}faxspeed.datatype" />
 *       &lt;attribute name="ecm" type="{}boolean.datatype" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendobj",
    "hdrfooter",
    "rxpoll",
    "faxstart",
    "faxnegotiate",
    "faxpagedone",
    "faxobjectdone",
    "faxopcomplete",
    "faxpollstart"
})
public class Faxsend
    extends PrimitiveType
{

    protected List<SendobjType> sendobj;
    protected HdrfooterType hdrfooter;
    protected Faxsend.Rxpoll rxpoll;
    protected Object faxstart;
    protected Object faxnegotiate;
    protected Object faxpagedone;
    protected Object faxobjectdone;
    protected Object faxopcomplete;
    protected Object faxpollstart;
    @XmlAttribute(name = "lclid")
    protected String lclid;
    @XmlAttribute(name = "minspeed")
    protected String minspeed;
    @XmlAttribute(name = "maxspeed")
    protected String maxspeed;
    @XmlAttribute(name = "ecm")
    protected BooleanDatatype ecm;

    /**
     * Gets the value of the sendobj property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sendobj property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSendobj().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SendobjType }
     * 
     * 
     */
    public List<SendobjType> getSendobj() {
        if (sendobj == null) {
            sendobj = new ArrayList<SendobjType>();
        }
        return this.sendobj;
    }

    /**
     * Gets the value of the hdrfooter property.
     * 
     * @return
     *     possible object is
     *     {@link HdrfooterType }
     *     
     */
    public HdrfooterType getHdrfooter() {
        return hdrfooter;
    }

    /**
     * Sets the value of the hdrfooter property.
     * 
     * @param value
     *     allowed object is
     *     {@link HdrfooterType }
     *     
     */
    public void setHdrfooter(HdrfooterType value) {
        this.hdrfooter = value;
    }

    /**
     * Gets the value of the rxpoll property.
     * 
     * @return
     *     possible object is
     *     {@link Faxsend.Rxpoll }
     *     
     */
    public Faxsend.Rxpoll getRxpoll() {
        return rxpoll;
    }

    /**
     * Sets the value of the rxpoll property.
     * 
     * @param value
     *     allowed object is
     *     {@link Faxsend.Rxpoll }
     *     
     */
    public void setRxpoll(Faxsend.Rxpoll value) {
        this.rxpoll = value;
    }

    /**
     * Gets the value of the faxstart property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFaxstart() {
        return faxstart;
    }

    /**
     * Sets the value of the faxstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFaxstart(Object value) {
        this.faxstart = value;
    }

    /**
     * Gets the value of the faxnegotiate property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFaxnegotiate() {
        return faxnegotiate;
    }

    /**
     * Sets the value of the faxnegotiate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFaxnegotiate(Object value) {
        this.faxnegotiate = value;
    }

    /**
     * Gets the value of the faxpagedone property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFaxpagedone() {
        return faxpagedone;
    }

    /**
     * Sets the value of the faxpagedone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFaxpagedone(Object value) {
        this.faxpagedone = value;
    }

    /**
     * Gets the value of the faxobjectdone property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFaxobjectdone() {
        return faxobjectdone;
    }

    /**
     * Sets the value of the faxobjectdone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFaxobjectdone(Object value) {
        this.faxobjectdone = value;
    }

    /**
     * Gets the value of the faxopcomplete property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFaxopcomplete() {
        return faxopcomplete;
    }

    /**
     * Sets the value of the faxopcomplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFaxopcomplete(Object value) {
        this.faxopcomplete = value;
    }

    /**
     * Gets the value of the faxpollstart property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFaxpollstart() {
        return faxpollstart;
    }

    /**
     * Sets the value of the faxpollstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFaxpollstart(Object value) {
        this.faxpollstart = value;
    }

    /**
     * Gets the value of the lclid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLclid() {
        return lclid;
    }

    /**
     * Sets the value of the lclid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLclid(String value) {
        this.lclid = value;
    }

    /**
     * Gets the value of the minspeed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinspeed() {
        return minspeed;
    }

    /**
     * Sets the value of the minspeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinspeed(String value) {
        this.minspeed = value;
    }

    /**
     * Gets the value of the maxspeed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxspeed() {
        return maxspeed;
    }

    /**
     * Sets the value of the maxspeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxspeed(String value) {
        this.maxspeed = value;
    }

    /**
     * Gets the value of the ecm property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanDatatype }
     *     
     */
    public BooleanDatatype getEcm() {
        return ecm;
    }

    /**
     * Sets the value of the ecm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanDatatype }
     *     
     */
    public void setEcm(BooleanDatatype value) {
        this.ecm = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rcvobj" type="{}rcvobjType" maxOccurs="unbounded"/>
     *         &lt;element name="hdrfooter" type="{}hdrfooterType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="rmtid" use="required" type="{}faxid.datatype" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rcvobj",
        "hdrfooter"
    })
    public static class Rxpoll {

        @XmlElement(required = true)
        protected List<RcvobjType> rcvobj;
        protected HdrfooterType hdrfooter;
        @XmlAttribute(name = "rmtid", required = true)
        protected String rmtid;

        /**
         * Gets the value of the rcvobj property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rcvobj property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRcvobj().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RcvobjType }
         * 
         * 
         */
        public List<RcvobjType> getRcvobj() {
            if (rcvobj == null) {
                rcvobj = new ArrayList<RcvobjType>();
            }
            return this.rcvobj;
        }

        /**
         * Gets the value of the hdrfooter property.
         * 
         * @return
         *     possible object is
         *     {@link HdrfooterType }
         *     
         */
        public HdrfooterType getHdrfooter() {
            return hdrfooter;
        }

        /**
         * Sets the value of the hdrfooter property.
         * 
         * @param value
         *     allowed object is
         *     {@link HdrfooterType }
         *     
         */
        public void setHdrfooter(HdrfooterType value) {
            this.hdrfooter = value;
        }

        /**
         * Gets the value of the rmtid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRmtid() {
            return rmtid;
        }

        /**
         * Sets the value of the rmtid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRmtid(String value) {
            this.rmtid = value;
        }

    }

}
