//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 04:34:21 PM EDT 
//


package com.dialogic.xms.msml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hdrfooterstyle.datatype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="hdrfooterstyle.datatype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="append"/>
 *     &lt;enumeration value="overlay"/>
 *     &lt;enumeration value="replace"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "hdrfooterstyle.datatype")
@XmlEnum
public enum HdrfooterstyleDatatype {

    @XmlEnumValue("append")
    APPEND("append"),
    @XmlEnumValue("overlay")
    OVERLAY("overlay"),
    @XmlEnumValue("replace")
    REPLACE("replace");
    private final String value;

    HdrfooterstyleDatatype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HdrfooterstyleDatatype fromValue(String v) {
        for (HdrfooterstyleDatatype c: HdrfooterstyleDatatype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
