//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 04:34:21 PM EDT 
//


package com.dialogic.xms.msml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hdrfooter.datatype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="hdrfooter.datatype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="header"/>
 *     &lt;enumeration value="footer"/>
 *     &lt;enumeration value="autohdr"/>
 *     &lt;enumeration value="nohdr"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "hdrfooter.datatype")
@XmlEnum
public enum HdrfooterDatatype {

    @XmlEnumValue("header")
    HEADER("header"),
    @XmlEnumValue("footer")
    FOOTER("footer"),
    @XmlEnumValue("autohdr")
    AUTOHDR("autohdr"),
    @XmlEnumValue("nohdr")
    NOHDR("nohdr");
    private final String value;

    HdrfooterDatatype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HdrfooterDatatype fromValue(String v) {
        for (HdrfooterDatatype c: HdrfooterDatatype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
