//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 04:34:21 PM EDT 
//


package com.dialogic.xms.msml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for streamDir.datatype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="streamDir.datatype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="to-id1"/>
 *     &lt;enumeration value="from-id1"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "streamDir.datatype")
@XmlEnum
public enum StreamDirDatatype {

    @XmlEnumValue("to-id1")
    TO_ID_1("to-id1"),
    @XmlEnumValue("from-id1")
    FROM_ID_1("from-id1");
    private final String value;

    StreamDirDatatype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StreamDirDatatype fromValue(String v) {
        for (StreamDirDatatype c: StreamDirDatatype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
